Repository WildCodeSchool-2023-09/remfr-php-p3-streetarthunter, pull requests merged in 2024-01, with the labels that each got.

#5 S3 us9 add navbar1
  assets/app.js
  assets/controllers/navbar.js
  assets/images/S.A.H5.png
  assets/images/connection.png
  assets/images/menu-burger-open.png
  assets/images/menu-burger.png
  assets/styles/_navbar1.scss
  assets/styles/app.scss
  assets/styles/index.scss
  templates/base.html.twig
  templates/home/index.html.twig
  templates/includes/_navbar1.html.twig
Labels: enhancement

#6 S3 us10 add navbar2
  assets/images/accueil.png
  assets/images/carte.png
  assets/styles/app.scss
  assets/styles/navbar2.scss
  templates/base.html.twig
  templates/includes/_navbar2.html.twig
Labels: conflicts

#7 creation du footer
  assets/styles/_footer.scss
  assets/styles/app.scss
  templates/base.html.twig
  templates/includes/_footer.html.twig
Labels: Reviewers missing, conflicts

#8 rectificatif bugs d'affichage navbar
  assets/styles/navbar2.scss
  templates/base.html.twig
Labels: Bug_fixed

#11 Fix navbar
  assets/images/Vincent.png
  assets/styles/_footer.scss
  assets/styles/_navbar1.scss
  assets/styles/app.scss
  assets/styles/galery.scss
  assets/styles/navbar2.scss
  src/Controller/GaleryController.php
  templates/base.html.twig
  templates/home/galery.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar1.html.twig
  templates/includes/_navbar2.html.twig
Labels: Bug_fixed

#13 rectificatif de la navbar et finalisation de la galerie
  assets/styles/app.scss
  assets/styles/galery.scss
  templates/home/galery.html.twig
  templates/includes/_navbar1.html.twig
Labels: enhancement, Bug_fixed

#14 S3 us page home
  assets/styles/app.scss
  assets/styles/index.scss
  templates/home/index.html.twig
Labels: enhancement, Bug_fixed

#15 formulaire inscription back 050124
  assets/styles/registration_form.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  migrations/Version20240103111522.php
  migrations/Version20240103144552.php
  script.sh
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/registration/register.html.twig
Labels: Reviewers missing

#18 S4 us page mentions legales
  assets/styles/_navbar1.scss
  assets/styles/app.scss
  assets/styles/legal.scss
  assets/styles/navbar2.scss
  assets/styles/profil.scss
  src/Controller/LegalController.php
  src/Controller/ProfilController.php
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/includes/_navbar1.html.twig
  templates/legal/index.html.twig
  templates/user/profil.html.twig
Labels: enhancement

#17 S3 us5 add inscription2
  assets/styles/app.scss
  assets/styles/register.scss
  assets/styles/registration_form.scss
  assets/styles/root.scss
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: conflicts

#22 S4 us ranking page3
  assets/styles/_footer.scss
  assets/styles/_navbar1.scss
  assets/styles/index.scss
  assets/styles/navbar2.scss
  assets/styles/ranking.scss
  src/Controller/RankingController.php
  templates/ranking/index.html.twig
Labels: enhancement, Reviewers missing, Bug_fixed

#20 S4 us ranking page
  assets/styles/_footer.scss
  assets/styles/_navbar1.scss
  assets/styles/index.scss
  assets/styles/navbar2.scss
  assets/styles/ranking.scss
  src/Controller/RankingController.php
  templates/home/ranking.html.twig
  templates/ranking/index.html.twig
Labels: bug, conflicts

#23 fix bug + route
  templates/includes/_footer.html.twig
  templates/includes/_navbar1.html.twig
Labels: conflicts, Bug_fixed

#27 fixtures à jour avec faker
  composer.json
  composer.lock
  migrations/Version20240122142440.php
  script.sh
  src/DataFixtures/AppFixtures.php
  src/DataFixtures/ArtistFixtures.php
  src/DataFixtures/ArtworkFixtures.php
  src/DataFixtures/ImageFixtures.php
  src/DataFixtures/PartnerFixtures.php
  src/DataFixtures/PointFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Artwork.php
  templates/home/galery.html.twig
Labels: conflicts

#30 S4 us20 add carte
  assets/app.js
  assets/images/graphIcon.png
  assets/images/ombreIcon.png
  assets/styles/app.scss
  assets/styles/carte.scss
  bash.exe.stackdump
  src/Controller/CarteController.php
  src/DataFixtures/AppFixtures.php
  templates/arts/artwork.html.twig
  templates/base.html.twig
  templates/carte/index.html.twig
  templates/includes/_navbar2.html.twig
Labels: enhancement

#34 S5 us2 add gestion users
  assets/admin.js
  assets/styles/admin/admin.scss
  assets/styles/admin/adminUser.scss
  assets/styles/ranking.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp-paginator.yaml
  config/packages/security.yaml
  src/Controller/Admin/AdminUserController.php
  src/Controller/CarteController.php
  src/Controller/RegistrationController.php
  src/DataFixtures/UserFixtures.php
  src/Form/UserType.php
  src/Repository/UserRepository.php
  src/Security/LoginAuthenticator.php
  symfony.lock
  templates/admin.html.twig
  templates/admin/admin_user/_delete_form.html.twig
  templates/admin/admin_user/_form.html.twig
  templates/admin/admin_user/edit.html.twig
  templates/admin/admin_user/index.html.twig
  templates/admin/admin_user/show.html.twig
  templates/includes/_navbar1.html.twig
  templates/ranking/index.html.twig
  webpack.config.js
Labels: enhancement

#36 S6 us fix camera
  .gitignore
  assets/styles/app.scss
  assets/styles/camera.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  migrations/Version20240124150909.php
  migrations/Version20240124151807.php
  public/upload/image/artwork/1706176630313477994032132709410-65b230a09c3e7275901910.jpg
  public/upload/image/artwork/1706176630313477994032132709410-65b230addbbe6260118559.jpg
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095800-65b2208c319cf647151040.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095800-65b222906a3dc149507406.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095800-65b222cddf5ee024887386.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095800-65b222d779432859948182.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095800-65b222e68dd04969990423.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095800-65b223e6584c8576564933.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095800-65b22e8629a0d692829514.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095946-65b22540d0810163630751.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095946-65b225a0d13e9095975330.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095946-65b225b716eb1821546957.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095946-65b225cb33da5446482924.png
  public/upload/image/artwork/capture-d-ecran-2024-01-05-095946-65b2297f82252477236963.png
  public/upload/image/artwork/capture-d-ecran-2024-01-12-120918-65b224e5370bb580343193.png
  public/upload/image/artwork/image-65b23118cd47e449529561.jpg
  public/upload/image/artwork/image-65b233a36284d562823820.jpg
  src/Controller/CameraController.php
  src/Entity/Image.php
  src/Form/ImageType.php
  symfony.lock
  templates/camera/index.html.twig
Labels: enhancement
